header:
  productName: Commerce Hub
  productionDescription: >
        Built to deliver innovation through simple, fast integrations, the Commerce Hub is 
        the most powerful omnichannel platform. With developer-friendly, flexible 
        communication standards, unified APIs, and pre-certified integrations the Commerce 
        Hub reduces development time and accelerates speed to market.

        A true single entry point and intelligent orchestration layer means you now have 
        access to the latest, most popular commerce experiences through your existing 
        infrastructure. With less ongoing maintenance and fewer operational costs, you can 
        focus on creating new ways for consumers to discover and interact with you.
  image: 
    link: "/assets/images/commercehub.jpg"
    altText: CommerceHub
steps:  
  learnSteps:
    - title: Learn
      description: >
        Quickly find the right integration, experiment with our APIs, and discover guided 
        tutorials for your next project.
    - title:
      description:
      link:
    - title:
      description:
      link:
  buildSteps:
    - title: Build
      description: >
        Leverage sample code, comprehensive SDKs, plug-ins, and sandbox testing to 
        complete your project fast.
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
  validateSteps:
    - title: Validate
      description: >
        Identify parts of your project that need attention and solutions end-to-end in 
        our advanced Sandbox.
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
  deploySteps:
    - title: deploy
      description: >
        Submit your project for automated certification and deploy to Production.
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
featuredFeatures:
  - title: Tokenization
    description: >
      Remove sensitive customer data from your environment and reduce PCI compliance 
      scope. Transaction data is protected by a randomly-generated identifier known as a 
      "token".
    tags: ["", ""]
    bullets:
      bullet1: Increase payment security and reduce risk
      bullet2: No need to store personal customer information
      bullet3: Less operational costs
      bullet4: Improved customer experience
    links:
      link1: "***insert links***"
  - title: Apple Pay
    description: >
      One of the most popular mobile payment and digital wallets. Customers can make 
      payments in-store, mobile or online. To leverage, customers use an Apple devices 
      - iPhone, Apple Watch, iPad, Mac, etc.
    tags: ["", ""]
    bullets:
      bullet1: Faster acceptance than credit or debit
      bullet2: Biometric security
      bullet3: Global offering and acceptance
    links:
      link1: "***insert links***"
  - title: API Integration
    description: >
      Leverage your existing infastructure and UI to accept payments online, in-store or on 
      mobile devices.
    tags: ["", ""]
    bullets:
      bullet1: Modern technology stack
      bullet2: Automated backoffice
      bullet3: Fast testing, certification and implementation
    links:
      link1: "***insert links***"
benefits:
  - title: Transform Customer Experiences
    description: >
      Pre-certified integrations to value added solutions and third-party providers 
      that power next-generation commerce experiences.
  - title: Accelerate Revenue
    description: Intellegent orchestration layer that reduces code complexity and operational costs.
  - title: Optimize Commerce
    description: Backoffice automation with a modern set of tools and APIs.   
featuredAPIs:
  - name: API name1
    description: 1 description
    type: POST
    route: /payments
    language: Curl
    link: link to API Explorer
  - name: API name2
    description: 1 description
    type: POST
    route: /orders
    language: Curl
    link: link to API Explorer 
  - name: API name3
    description: 1 description
    type: POST
    route: /cancel
    language: Curl
    link: link to API Explorer  
useCases:
  - title: Contactless Payments
    subtitle: Apple Pay
    description: >
      Accept contactless, touchless payments Customers can One of the most popular 
      mobile payment and digital wallets. Customers can make payments in-store, mobile 
      or online. To leverage, customers use an Apple devices - iPhone, Apple Watch, iPad, 
      Mac, etc.
    bullets:
      bullet1: Faster acceptance than credit or debit
      bullet2: Biometric security
      bullet3: Global offering and acceptance
    link:
  - title:
    subtitle:
    description:
    bullets:
    bullet1: 
    bullet2: 
    bullet3: 
    link:
